config/routes.rb
Rails.application.routes.draw do

  resources :highscores

  resources :levels do
    get 'upload'
    resources :highscores
  end

  get 'static_pages/home'
  get 'static_pages/download'
  get 'static_pages/privacy_policy'
  get '/home', to: 'static_pages#home'
  get '/download', to: 'static_pages#download'
  get '/privacy_policy', to: 'static_pages#privacy_policy'


  root 'static_pages#home'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/highscore.rb
class Highscore < ApplicationRecord

  belongs_to :level
  #validates :name, :uniqueness => true
  validates_presence_of :score
  validates_presence_of :time
  validates_presence_of :name
  validates_length_of :name, :minimum => 1
  validates_length_of :name, :maximum => 12
end

app/models/level.rb
class Level < ApplicationRecord
  def to_param  # overridden
    name
  end
  has_many :highscores, dependent: :destroy

  validates_presence_of :name, :gamemode, :image_url

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
  before_action :set_highscore, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "Spartanfox", password: "toidzBlock", except: [:index, :show]
  # GET /highscores
  # GET /highscores.json
  def index
    @level = Level.find_by_name(params[:level_id])
    @highscores = @level.highscores
    @start = 0
    @end = 10
    if params.has_key?(:page)
      @start = params[:page].to_i
    end
    @highscores = @highscores.sort{|a,b| b.score.to_i <=> a.score.to_i}
    @highscores = @highscores[@start,@end]
  end

  # GET /highscores/1
  # GET /highscores/1.json
  def show

  end

  # GET /highscores/new
  def new
    @level = Level.find_by_name(params[:level_id])
    @highscore = @level.highscores.new
  end

  # GET /highscores/1/edit
  def edit
    @level = Level.find_by_name(params[:level_id])
  end



  # POST /highscores
  # POST /highscores.json
  def create
    @level = Level.find_by_name(params[:level_id])
    @highscore = @level.highscores.new(highscore_params)
    @highscores = @level.highscores
    @highscores.each do |highscore|
      if highscore.name == @highscore.name
        if @highscore.score > highscore.score
          highscore.update(highscore_params)
          @highscore = highscore
        else
          @highscore.score = nil
          break
        end
      end
    end
    if !!@highscore.score
      respond_to do |format|
        if @highscore.save
          format.html { redirect_to level_highscores_path(Level.find(@highscore.level_id), format: :json), notice: 'Highscore was successfully created.' }
          format.json { render :show, status: :created, location: @highscore }
        else
          format.html { render :new }
          format.json { render json: @highscore.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to level_highscores_path(Level.find(@highscore.level_id), format: :json)
    end
  end

  # PATCH/PUT /highscores/1
  # PATCH/PUT /highscores/1.json
  def update
    respond_to do |format|
      if @highscore.update(highscore_params)
        format.html { redirect_to level_highscores_path(Level.find(@highscore.level_id), format: :json), notice: 'Highscore was successfully updated.' }
        format.json { render :show, status: :ok, location: @highscore }
      else
        format.html { render :edit }
        format.json { render json: @highscore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /highscores/1
  # DELETE /highscores/1.json
  def destroy
    @highscore.destroy
    respond_to do |format|
      format.html { redirect_to level_path(Level.find_by_name(params[:level_id])), notice: 'Highscore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_highscore
      @level = Level.find_by_name(params[:level_id])
      @highscore = @level.highscores.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def highscore_params
      params.require(:highscore).permit(:name, :time, :score)
    end
end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  before_action :set_level, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "Spartanfox", password: "toidzBlock", except: [:upload, :index, :show]
  # GET /levels
  # GET /levels.json
  def index
    @levels = Level.all
  end

  # GET /levels/1
  # GET /levels/1.json
  def show
    @highscores = @level.highscores.sort{|a,b| b.score.to_i <=> a.score.to_i}
  end

  # GET /levels/new
  def new
    @level = Level.new
  end

  # GET /levels/1/edit
  def edit
  end

  def upload
    @level = Level.find_by_name(params[:level_id])
    @highscore = @level.highscores.new(highscore_params)
    @highscores = @level.highscores
    @highscores.each do |highscore|
      if highscore.name.downcase == @highscore.name.downcase
        if @highscore.score >= highscore.score
          highscore.update(highscore_params)
          @highscore = highscore
          break
        else
          @highscore.score = nil
          break
        end
      end
    end
    if !!@highscore.score
      @highscore.save
    end
    redirect_to level_highscores_path(Level.find(@highscore.level_id), format: :json)
  end

  # POST /levels
  # POST /levels.json
  def create
    @level = Level.new(level_params)

    respond_to do |format|
      if @level.save
        format.html { redirect_to @level, notice: 'Level was successfully created.' }
        format.json { render :show, status: :created, location: @level }
      else
        format.html { render :new }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /levels/1
  # PATCH/PUT /levels/1.json
  def update
    respond_to do |format|
      if @level.update(level_params)
        format.html { redirect_to @level, notice: 'Level was successfully updated.' }
        format.json { render :show, status: :ok, location: @level }
      else
        format.html { render :edit }
        format.json { render json: @level.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /levels/1
  # DELETE /levels/1.json
  def destroy
    @level.destroy
    respond_to do |format|
      format.html { redirect_to levels_url, notice: 'Level was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_level
      @level = Level.find_by_name(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def level_params
      params.require(:level).permit(:name, :gamemode, :image_url)
    end

    def highscore_params
      params.require(:highscore).permit(:name, :time, :score)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/highscores_helper.rb
module HighscoresHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/highscores/_form.html.erb
<%= simple_form_for([@level, @highscore], html: { class: 'form-horizontal' }) do |form| %>
  <% if @highscore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(highscore.errors.count, "error") %> prohibited this highscore from being saved:</h2>
      <ul>
      <% highscore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.input :name  %>
  <%= form.input :time  %>
  <%= form.input :score %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/highscores/edit.html.erb
<h1>Editing Highscore</h1>

<%= render 'form', highscore: @highscore %>
<%= button_to 'Back', level_path(@level), :method => :get %>
<%= button_to "Delete", [@level, @highscore], method: :delete %>

app/views/highscores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Highscores</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @highscores.each do |highscore| %>
      <tr>
        <td><%= link_to 'Show', highscore %></td>
        <td><%= link_to 'Edit', edit_highscore_path(highscore) %></td>
        <td><%= link_to 'Destroy', highscore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Highscore', new_highscore_path %>

app/views/highscores/new.html.erb
<h1>New Highscore</h1>

<%= render 'form', highscore: @highscore %>

<%= link_to 'Back', level_path(@level) %>

app/views/highscores/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_highscore_path(@highscore) %> |
<%= link_to 'Back', highscores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocktoidz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <center>
      <img src="https://lh3.googleusercontent.com/-NzN3QjKVAA8/WooUYlWaScI/AAAAAAAAAIc/T5Lj6gox9nApU0CnFKnivOJuOC2QtaXawCEwYBhgL/w700-h200-p/BANNIR.png" class="img-rounded" alt="Blocktoidz" >
    </center>
    <br>
    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Blocktoidz</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="<%= current_page?(home_path    )? "active" : ""%>"><%= link_to "Home", home_path         %></li>
      <li class="<%= current_page?(levels_path  )? "active" : ""%>"><%= link_to "Levels", levels_path     %></li>
      <li class="<%= current_page?(download_path)? "active" : ""%>"><%= link_to "Download", download_path %></li>
    </ul>
  </div>
</nav>
    <div class="jumbotron" style=" padding-left: 10em; padding-right: 10em;">
      <%= yield %>
    </div>
  </body>
  <footer class="footer">
    <center>
     A website by spartanfox productions 2018
    </center>
  </footer>

</html>

app/views/levels/_form.html.erb
<%= simple_form_for(@level, html: { class: 'form-horizontal' }) do |form| %>
  <% if @level.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@level.errors.count, "error") %> prohibited this level from being saved:</h2>
      <ul>
      <% @level.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.input :name      %>
  <%= form.input :gamemode  %>
  <%= form.input :image_url %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/levels/edit.html.erb
<h1>Editing Level</h1>

<%= render 'form', level: @level %>

<%= link_to 'Show', @level %> |
<%= link_to 'Back', levels_path %>

app/views/levels/index.html.erb
<p id="notice"><%= notice %></p>

<div class="list-group">
    <div class="list-group-item list-group-item-action flex-column align-items-start active">
      <div class="d-flex w-100 justify-content-start">
        <h2 class="mb-1">Blocktoidz Levels</h2>
      </div>
    </div>
    <% @levels.each do |level| %>
      <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex justify-content-around ">
          <h3 class="mb-1">
            <%= link_to 'View highscores', level_path(level), class:"btn btn-default"%>
            <%= level.name%>
          </h3>
        </div>
        <p class="mb-1"><%= level.gamemode%></p>
        <small class="text-muted"><%= level.highscores.size%> Highscores</small>
        <small class="text-muted"><%= level.created_at.strftime("%D - %I:%M %p")%></small>
      </div>
    <%end%>
  </div>

app/views/levels/new.html.erb
<h1>New Level</h1>

<%= render 'form', level: @level %>

<%= link_to 'Back', levels_path %>

app/views/levels/show.html.erb
<p id="notice"><%= notice %></p>

<div class="list-group">
    <div class="list-group-item list-group-item-action flex-column align-items-start active">
      <div class="d-flex w-100 justify-content-start">
        <h2 class="mb-1">
          <div>
            <%= @level.name %> Highscores
            <%#= link_to 'Edit', edit_level_path(@level) %> |
            <%= link_to 'Back', levels_path %>
          </div>
          <%#= link_to "Upload test highscore", level_upload_path(@level, :highscore => { :name => "Spartanfox", :time => "00:01:43", :score => 1 }) %>
        </h2>
      </div>
    </div>
    <% @highscores.each do |highscore| %>
      <div class="list-group-item list-group-item-action flex-column align-items-start">
        <div class="d-flex justify-content-around ">
          <h3 class="mb-1">
            <%= @highscores.find_index(highscore)+1 %><%= link_to ":" , edit_level_highscore_path(@level, highscore)%> <%= highscore.name %> <%= highscore.time %> <%= highscore.score %> 
          </h3>
        </div>
      </div>
    <%end%>
  </div>

app/views/static_pages/download.html.erb
<h1>You can download blocktoidz on the play store</h1>
<a href="https://play.google.com/store/apps/details?id=com.spartanfox.blocktoidz&hl=en"
    class="btn btn-primary btn-lg btn-block">
    Download
</a>

app/views/static_pages/home.html.erb
<div class="container">
  <center>
  <h1>Welcome to Blocktoidz</h1>

    <p>
      <h3>
        Blocktoidz is a action puzzle game similar to tetris, however using complex triangular pieces<br>
        allowing for fun and interesting gameplay.
      </h3>
    </p>
    <img src="https://lh3.googleusercontent.com/JoTA-SUggwMABsObWhBhrEmNndrlIYXcD2Lw5etyljGhkhbY8ItO418AtLOGwfHmuF8=h400" class="img-rounded" alt="Blocktoidz" >
    <img src="https://lh3.googleusercontent.com/-xrQ-VBPzC7UMJbNnaPNOVAVOZHqqWhDfb3SC7jiYjTErK2-a2TD-5VNvhJpj5mJxpU=h400" class="img-rounded" alt="Blocktoidz" >
    <p>
      <h3>
        Blocktoidz has alot of levels and variety including different themes and gamemodes.<br>
        One gamemode is breaker where you must destroy an object within the level as fast as you can.
      </h3>
    </p>
    <img src="https://lh3.googleusercontent.com/B1Aj-l_BCAyU6uyYFfXAcxTe71qIngGlx_qmD5TW-YOdXsuC4sgqYhK-lGLiA3QyVA=h400" class="img-rounded" alt="Blocktoidz" >
    <img src="https://lh3.googleusercontent.com/W1WyTdIjMreMKCNOhcrUmzt1FAiYb_8JToidvYFwTNwIqshWkPpj-4YPc1f0jTCMLSU=h400" class="img-rounded" alt="Blocktoidz" >
    <img src="https://lh3.googleusercontent.com/KCUzdpSclCXnHM60_BJgNFRwoBQpIibGXibcsI2uqNkjsLWE1VvaBpD9oHiUwQcWa237=h400" class="img-rounded" alt="Blocktoidz" >
    <p>
      <h3>
        Once you have completed a level you can enter your name and view it in the highscores,<br>
        if the level is a breaker level once you have sucsesfully completed it then you will<br>
        unlock the next level.
      </h3>
    </p>
    <img src="https://lh3.googleusercontent.com/6nEOlrkg-6t6noIM8zKUFE-UkTNvibIAv_Piq2UHMSA2hJYq0aBVGrySCTlw_7GKPns=h400" class="img-rounded" alt="Blocktoidz" >
    <img src="https://lh3.googleusercontent.com/YlmjpkBOi-WMXlQLNhvtVkTdaCl5-mfaxKEK2rwRATmBMMYo4KB5SqSiXsokt1uXxwE=h400" class="img-rounded" alt="Blocktoidz" >

  </center>
</div>

app/views/static_pages/privacy_policy.html.erb
<!DOCTYPE html><html> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width"> <title>Privacy Policy</title> <style>body{font-family: "Helvetica Neue", Helvetica, Arial, sans-serif; padding:1em;}</style></head> <body><h2>Privacy Policy</h2> <p> Spartanfox Productions built the Blocktoidz app as an Ad Supported app. This SERVICE is provided by Spartanfox Productions at no cost and is intended for use as is.
                  </p> <p>This page is used to inform website visitors regarding our policies with the collection, use, and
                    disclosure of Personal Information if anyone decided to use our Service.
                  </p> <p>If you choose to use our Service, then you agree to the collection and use of information in relation
                    to this policy. The Personal Information that we collect is used for providing and improving the
                    Service. We will not use or share your information with anyone except as described
                    in this Privacy Policy.
                  </p> <p>The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, which is accessible
                    at Blocktoidz unless otherwise defined in this Privacy Policy.
                  </p> <p><strong>Information Collection and Use</strong></p> <p>For a better experience, while using our Service, we may require you to provide us with certain
                    personally identifiable information, including but not limited to Username, Highscores, UID(Unique ID). The information that we request is will be retained by us and used as described in this privacy policy.
                  </p> <p>The app does use third party services that may collect information used to identify you.</p> <div><p>Link to privacy policy of third party service providers used by the app</p> <ul><li><a target="_blank" href="https://www.google.com/policies/privacy/">Google Play Services</a></li> <!----> <li><a target="_blank" href="https://firebase.google.com/policies/analytics">Firebase Analytics</a></li> <!----> <!----> <!----></ul></div> <p><strong>Log Data</strong></p> <p> We want to inform you that whenever you use our Service, in a case of an
                    error in the app we collect data and information (through third party products) on your phone
                    called Log Data. This Log Data may include information such as your device Internet Protocol (“IP”) address,
                    device name, operating system version, the configuration of the app when utilizing our Service,
                    the time and date of your use of the Service, and other statistics.
                  </p> <p><strong>Cookies</strong></p> <p>Cookies are files with small amount of data that is commonly used an anonymous unique identifier. These
                    are sent to your browser from the website that you visit and are stored on your device internal memory.
                  </p> <p>This Service does not use these “cookies” explicitly. However, the app may use third party code and libraries
                    that use “cookies” to collection information and to improve their services. You have the option to either
                    accept or refuse these cookies and know when a cookie is being sent to your device. If you choose to
                    refuse our cookies, you may not be able to use some portions of this Service.
                  </p> <p><strong>Service Providers</strong></p> <p> We may employ third-party companies and individuals due to the following reasons:</p> <ul><li>To facilitate our Service;</li> <li>To provide the Service on our behalf;</li> <li>To perform Service-related services; or</li> <li>To assist us in analyzing how our Service is used.</li></ul> <p> We want to inform users of this Service that these third parties have access to your
                    Personal Information. The reason is to perform the tasks assigned to them on our behalf. However, they
                    are obligated not to disclose or use the information for any other purpose.
                  </p> <p><strong>Security</strong></p> <p> We value your trust in providing us your Personal Information, thus we are striving
                    to use commercially acceptable means of protecting it. But remember that no method of transmission over
                    the internet, or method of electronic storage is 100% secure and reliable, and we cannot guarantee
                    its absolute security.
                  </p> <p><strong>Links to Other Sites</strong></p> <p>This Service may contain links to other sites. If you click on a third-party link, you will be directed
                    to that site. Note that these external sites are not operated by us. Therefore, we strongly
                    advise you to review the Privacy Policy of these websites. We have no control over
                    and assume no responsibility for the content, privacy policies, or practices of any third-party sites
                    or services.
                  </p> <p><strong>Children’s Privacy</strong></p> <p>These Services do not address anyone under the age of 13. We do not knowingly collect
                    personally identifiable information from children under 13. In the case we discover that a child
                    under 13 has provided us with personal information, we immediately delete this from
                    our servers. If you are a parent or guardian and you are aware that your child has provided us with personal
                    information, please contact us so that we will be able to do necessary actions.
                  </p> <p><strong>Changes to This Privacy Policy</strong></p> <p> We may update our Privacy Policy from time to time. Thus, you are advised to review
                    this page periodically for any changes. We will notify you of any changes by posting
                    the new Privacy Policy on this page. These changes are effective immediately after they are posted on
                    this page.
                  </p> <p><strong>Contact Us</strong></p> <p>If you have any questions or suggestions about our Privacy Policy, do not hesitate to contact
                    us.
                  </p> <p>This privacy policy page was created at <a target="_blank" href="https://privacypolicytemplate.net">privacypolicytemplate.net</a>                    and modified/generated by <a target="_blank" href="https://app-privacy-policy-generator.firebaseapp.com/">App Privacy Policy Generator</a></p></body></html>